name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:



  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci-provisioner
          ping: ${{ secrets.PM_IP }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        env:
          TF_VAR_proxmox_api_url: https://${{ secrets.PM_IP }}:8006/
          TF_VAR_proxmox_user: ${{ secrets.PM_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PM_PASSWORD }}

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_proxmox_api_url: https://${{ secrets.PM_IP }}:8006/
          TF_VAR_proxmox_user: ${{ secrets.PM_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PM_PASSWORD }}
          TF_VAR_vm_user: ${{ secrets.SSH_USERNAME }}
          TF_VAR_vm_password: ${{ secrets.SSH_PASSWORD }}
          TF_VAR_vm_ssh_key: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Generate Ansible Inventory
        shell: bash
        run: |               
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          cd terraform
          terraform output -json ansible_inventory | grep '^{' > ../tf_output.json
          cd ..          
          SSH_USER=$(jq -r '.username' tf_output.json)
          SSH_PASS=$(jq -r '.password' tf_output.json)          
          cat <<EOF > ansible/inventory.yml
          all:
            vars:
              ansible_user: "$SSH_USER"
              ansible_become_password: "$SSH_PASS"
              ansible_ssh_private_key_file: "/tmp/ssh_key"
              ansible_python_interpreter: "/usr/bin/python3.11"
            children:
          EOF
          jq -r '.vms | to_entries[] | "    " + .key + ":\n      hosts:\n" + ( [.value[] | "        " + .hostname + ":\n          ansible_host: " + .ip ] | join("\n") )' tf_output.json >> ansible/inventory.yml

      - name: Run Ansible Playbook
        shell: bash
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          cat ansible/inventory.yml
          # Run playbook         
          ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
        
        

     